// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP-y3kHYucHU3myJGA8mMe_wkVbT81J1s',
    appId: '1:170046400032:web:4bd6643fdd0518d0803e45',
    messagingSenderId: '170046400032',
    projectId: 'auth-system-d3f48',
    authDomain: 'auth-system-d3f48.firebaseapp.com',
    storageBucket: 'auth-system-d3f48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPd0D3Dnu3_Ec1gzw9dsIWhtwUBae8lAg',
    appId: '1:170046400032:android:be6dea1f10b037ed803e45',
    messagingSenderId: '170046400032',
    projectId: 'auth-system-d3f48',
    storageBucket: 'auth-system-d3f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2iY6RvUvX6SlLgwUVsULjW-2hGONO068',
    appId: '1:170046400032:ios:f84eba651a781c62803e45',
    messagingSenderId: '170046400032',
    projectId: 'auth-system-d3f48',
    storageBucket: 'auth-system-d3f48.firebasestorage.app',
    iosBundleId: 'com.example.authFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2iY6RvUvX6SlLgwUVsULjW-2hGONO068',
    appId: '1:170046400032:ios:f84eba651a781c62803e45',
    messagingSenderId: '170046400032',
    projectId: 'auth-system-d3f48',
    storageBucket: 'auth-system-d3f48.firebasestorage.app',
    iosBundleId: 'com.example.authFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP-y3kHYucHU3myJGA8mMe_wkVbT81J1s',
    appId: '1:170046400032:web:aeda0927c3e4a85e803e45',
    messagingSenderId: '170046400032',
    projectId: 'auth-system-d3f48',
    authDomain: 'auth-system-d3f48.firebaseapp.com',
    storageBucket: 'auth-system-d3f48.firebasestorage.app',
  );

}